version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: ./.publish
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test


